#!/bin/bash

rootdir="$(dirname $(cd $(dirname $BASH_SOURCE) && pwd))"
cd $rootdir

package="$1"

if [ "$package" == "" ] || [ ! -d packages/$package ]; then
  printf "\n[!] Package folder name specified is invalid { $package }\n\n"
  exit
fi

yarn build $package

printf "Publishing package to NPM { $package }\n"
# Add publish code here
echo
