#!/bin/bash

ROOTDIR="$(dirname $(cd $(dirname $BASH_SOURCE) && pwd))"

cd $ROOTDIR

source scripts/support

# BEGIN

set_global_packages $1

for package in "${PACKAGES[@]}"; do
  echo
  build_package_command $package
  release_package_command $package
  echo
done
echo

unset_global_packages
